### ISSUE TITLE
Modules naming/structure

### ISSUE THREAD

**Issue by mostaphaRoudsari** [ladybug-tools/ladybug-vtk#22]
Hi @devngc,

I had a chance to quickly check the library today and I should say that I find the modules really confusing. As a developer, it is really hard to know where to look for what. This might be because some of the modules are following the `ladybug-geometry` naming and some are following `ladybug-rhino`. Right now we have `from_ladybug2D`, `from_ladybugh3D` and then `to_vtk`. As a developer, I don't know where to start and what to expect. Do we still need the `to_vtk` module?

I personally like the approach in `ladybug-rhino` more to keep all the 2D and 3D geometry in the same module so I know where to go to find all of them: https://github.com/ladybug-tools/ladybug-rhino/blob/master/ladybug_rhino/fromgeometry.py

**Comment by devngc** [comment]
Hey @mostaphaRoudsari,

This is qualitative. I find the current approach very clear. As a developer you go to from_ladybug3d to convert ladybug3d objects to Polydata and you go to from_ladybug2d to convert ladybug2d objects to polydata. We still need to_vtk. It has functions that are not exactly mapped to a ladybug2d or ladybug3d objects.

Since this is qualitative, rather than debating I could just do what you want and that is dumping all the functions in long module named fromgeometry or do what you suggested [here](https://github.com/ladybug-tools/ladybug-vtk/issues/23)

**Comment by mostaphaRoudsari** [comment]
Hi @devngc! Thanks. Yes. Let's put it all in a single fie and try to be consistent between different libraries.
